/**
 * Default Lofi Scene Templates - PRODUCTION READY
 * All templates use correct SceneElement structure
 */

import { LofiTemplate } from '../../stores/lofiStore'

export const DEFAULT_TEMPLATES: LofiTemplate[] = [
  // 1. Cozy Study Room
  {
    id: 'cozy-room-1',
    name: 'Cozy Study Room',
    description: 'Warm study room with desk, books, and window view',
    category: 'CozyRoom',
    thumbnail: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    scene: {
      id: 'scene-1',
      name: 'Cozy Study Room',
      background: {
        id: 'bg-1',
        name: 'Warm Room Background',
        element_type: 'Background',
        x: 960,
        y: 540,
        scale: 1.0,
        rotation: 0,
        opacity: 1,
        z_index: 0,
        source: { type: 'Image', path: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1920&h=1080&fit=crop' },
        animations: [],
      },
      characters: [
        {
          id: 'char-1',
          name: 'Study Character',
          element_type: 'Character',
          x: 400,
          y: 300,
          scale: 1.2,
          rotation: 0,
          opacity: 1,
          z_index: 10,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop' },
          animations: ['subtle-sway'],
        },
      ],
      props: [
        {
          id: 'prop-1',
          name: 'Coffee Cup',
          element_type: 'Prop',
          x: 800,
          y: 500,
          scale: 0.5,
          rotation: 15,
          opacity: 1,
          z_index: 5,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=200&h=200&fit=crop' },
          animations: ['steam'],
        },
        {
          id: 'prop-2',
          name: 'Books',
          element_type: 'Prop',
          x: 1200,
          y: 450,
          scale: 0.8,
          rotation: -5,
          opacity: 1,
          z_index: 4,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300&h=200&fit=crop' },
          animations: [],
        },
      ],
      overlays: [],
      loop_settings: { duration: 60, auto_sync: true },
      created_at: new Date().toISOString(),
      modified_at: new Date().toISOString(),
    },
    customization_options: [],
    tags: ['study', 'cozy', 'warm', 'indoor'],
    popularity: 1250,
  },

  // 2. Rainy Window
  {
    id: 'rainy-window-1',
    name: 'Rainy Window View',
    description: 'City view through rain-covered window',
    category: 'RainyWindow',
    thumbnail: 'linear-gradient(135deg, #30cfd0 0%, #330867 100%)',
    scene: {
      id: 'scene-2',
      name: 'Rainy Window View',
      background: {
        id: 'bg-2',
        name: 'Rainy City Window',
        element_type: 'Background',
        x: 960,
        y: 540,
        scale: 1.0,
        rotation: 0,
        opacity: 1,
        z_index: 0,
        source: { type: 'Image', path: 'https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=1920&h=1080&fit=crop' },
        animations: [],
      },
      characters: [
        {
          id: 'char-2',
          name: 'Cat on Window Sill',
          element_type: 'Character',
          x: 1400,
          y: 600,
          scale: 0.7,
          rotation: 0,
          opacity: 0.9,
          z_index: 10,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=300&fit=crop' },
          animations: ['breathing'],
        },
      ],
      props: [
        {
          id: 'prop-3',
          name: 'Coffee Mug',
          element_type: 'Prop',
          x: 300,
          y: 800,
          scale: 0.6,
          rotation: 5,
          opacity: 1,
          z_index: 5,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1514481538271-cf9f99627ab4?w=200&h=200&fit=crop' },
          animations: ['steam'],
        },
        {
          id: 'prop-4',
          name: 'Plant',
          element_type: 'Prop',
          x: 1600,
          y: 400,
          scale: 0.9,
          rotation: 0,
          opacity: 0.85,
          z_index: 4,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?w=300&h=400&fit=crop' },
          animations: ['gentle-sway'],
        },
      ],
      overlays: [],
      loop_settings: { duration: 60, auto_sync: true },
      created_at: new Date().toISOString(),
      modified_at: new Date().toISOString(),
    },
    customization_options: [],
    tags: ['rain', 'window', 'chill', 'atmospheric'],
    popularity: 2100,
  },

  // 3. Night Cityscape
  {
    id: 'cityscape-1',
    name: 'Night Cityscape',
    description: 'Animated city skyline at night with lights',
    category: 'Cityscape',
    thumbnail: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
    scene: {
      id: 'scene-3',
      name: 'Night Cityscape',
      background: {
        id: 'bg-3',
        name: 'Night City Skyline',
        element_type: 'Background',
        x: 960,
        y: 540,
        scale: 1.0,
        rotation: 0,
        opacity: 1,
        z_index: 0,
        source: { type: 'Image', path: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1920&h=1080&fit=crop' },
        animations: [],
      },
      characters: [],
      props: [
        {
          id: 'prop-5',
          name: 'Moon',
          element_type: 'Prop',
          x: 1600,
          y: 200,
          scale: 0.4,
          rotation: 0,
          opacity: 0.9,
          z_index: 5,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1543722530-d2c3201371e7?w=200&h=200&fit=crop' },
          animations: ['glow'],
        },
        {
          id: 'prop-6',
          name: 'Flying Bird',
          element_type: 'Prop',
          x: 800,
          y: 400,
          scale: 0.2,
          rotation: -15,
          opacity: 0.7,
          z_index: 4,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=150&h=100&fit=crop' },
          animations: ['fly-across'],
        },
      ],
      overlays: [],
      loop_settings: { duration: 60, auto_sync: true },
      created_at: new Date().toISOString(),
      modified_at: new Date().toISOString(),
    },
    customization_options: [],
    tags: ['city', 'night', 'urban', 'skyline'],
    popularity: 1800,
  },

  // 4. Forest Clearing
  {
    id: 'nature-1',
    name: 'Forest Clearing',
    description: 'Peaceful forest clearing with fireflies',
    category: 'NatureScene',
    thumbnail: 'linear-gradient(135deg, #134e5e 0%, #71b280 100%)',
    scene: {
      id: 'scene-4',
      name: 'Forest Clearing',
      background: {
        id: 'bg-4',
        name: 'Forest Path',
        element_type: 'Background',
        x: 960,
        y: 540,
        scale: 1.0,
        rotation: 0,
        opacity: 1,
        z_index: 0,
        source: { type: 'Image', path: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1920&h=1080&fit=crop' },
        animations: [],
      },
      characters: [
        {
          id: 'char-3',
          name: 'Deer',
          element_type: 'Character',
          x: 1300,
          y: 550,
          scale: 0.6,
          rotation: -10,
          opacity: 0.85,
          z_index: 10,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1551775912-062fd17b2a46?w=400&h=500&fit=crop' },
          animations: ['subtle-movement'],
        },
      ],
      props: [
        {
          id: 'prop-7',
          name: 'Mushrooms',
          element_type: 'Prop',
          x: 400,
          y: 750,
          scale: 0.5,
          rotation: 0,
          opacity: 1,
          z_index: 5,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=200&h=200&fit=crop' },
          animations: [],
        },
        {
          id: 'prop-8',
          name: 'Fallen Log',
          element_type: 'Prop',
          x: 800,
          y: 650,
          scale: 1.1,
          rotation: 5,
          opacity: 0.9,
          z_index: 4,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1518406537624-3b4515bac6e4?w=600&h=300&fit=crop' },
          animations: [],
        },
      ],
      overlays: [],
      loop_settings: { duration: 60, auto_sync: true },
      created_at: new Date().toISOString(),
      modified_at: new Date().toISOString(),
    },
    customization_options: [],
    tags: ['nature', 'forest', 'peaceful', 'wildlife'],
    popularity: 1600,
  },

  // 5. Space Station
  {
    id: 'space-1',
    name: 'Space Station View',
    description: 'View from space station with Earth in distance',
    category: 'SpaceTheme',
    thumbnail: 'linear-gradient(135deg, #141e30 0%, #243b55 100%)',
    scene: {
      id: 'scene-5',
      name: 'Space Station View',
      background: {
        id: 'bg-5',
        name: 'Space View',
        element_type: 'Background',
        x: 960,
        y: 540,
        scale: 1.0,
        rotation: 0,
        opacity: 1,
        z_index: 0,
        source: { type: 'Image', path: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=1920&h=1080&fit=crop' },
        animations: [],
      },
      characters: [
        {
          id: 'char-4',
          name: 'Astronaut',
          element_type: 'Character',
          x: 700,
          y: 500,
          scale: 0.8,
          rotation: 5,
          opacity: 1,
          z_index: 10,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1608889335941-32ac5f2041b9?w=400&h=600&fit=crop' },
          animations: ['float'],
        },
      ],
      props: [
        {
          id: 'prop-9',
          name: 'Earth',
          element_type: 'Prop',
          x: 1400,
          y: 300,
          scale: 0.6,
          rotation: 0,
          opacity: 1,
          z_index: 5,
          source: { type: 'Image', path: 'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=400&h=400&fit=crop' },
          animations: ['rotate-slow'],
        },
      ],
      overlays: [],
      loop_settings: { duration: 60, auto_sync: true },
      created_at: new Date().toISOString(),
      modified_at: new Date().toISOString(),
    },
    customization_options: [],
    tags: ['space', 'sci-fi', 'astronaut', 'cosmic'],
    popularity: 1950,
  },

  // 6. Blank Canvas
  {
    id: 'blank-canvas',
    name: 'Blank Canvas',
    description: 'Start from scratch with a blank scene',
    category: 'Custom',
    thumbnail: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    scene: {
      id: 'scene-blank',
      name: 'Blank Scene',
      characters: [],
      props: [],
      overlays: [],
      loop_settings: { duration: 60, auto_sync: true },
      created_at: new Date().toISOString(),
      modified_at: new Date().toISOString(),
    },
    customization_options: [],
    tags: ['blank', 'custom', 'scratch'],
    popularity: 500,
  },
]
